# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.omnibus.chef_version = "11.16.2"

  config.vm.box = "opscode-centos-6.5"
  config.vm.box_url = "http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-6.5_chef-provisionerless.box"

  config.vm.provider :virtualbox do |vb|
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "512"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

  config.vm.provision :chef_solo do |chef|
    chef.node_name = "mybox"
    chef.cookbooks_path = "../../cookbooks"
    chef.roles_path = "../../roles"
    chef.data_bags_path = "../../data_bags"
    chef.encrypted_data_bag_secret_key_path = "../../insecure_data_bag_key"

    chef.add_role "base"
    chef.add_recipe "hostname-test-cookbook"

    chef.verbose_logging = true
    chef.log_level = :debug
  end
end
